# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_photo:                  "true"
resume_name:                    "Mohammed Shoeb"
resume_title:                   "Student/Learner"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sk8147268@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "7023027812"
resume_contact_address:         "13 Pragati Nagar Police Line, Kota Rajasthan"

resume_header_contact_info:     "13 Pragati Nagar Police Line, Kota Rajasthan • 7023027812 • sk8147268@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Adaptable and innovative BTech final year student, equipped with a good foundation in programming languages, software development, and problem-solving. Eager to contribute technical expertise and a passion for cutting-edge technologies to a dynamic team in the field of computer science and technology.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
#resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Shoeb0263"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mohammed-shoeb-a01a141a9"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://linqapp.com/mohammed_shoeb"
 # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
